### ISSUE TITLE
Pill images

### ISSUE THREAD

**Issue by mduvall** [HHS/pillbox_docs#4]
The data page says the pill images will be available for download around August 2013, is there any ETA for that?

**Comment by ghost** [comment]
Speaking as the project manager of Pillbox, here's what's keeping us from providing image library downloads.
1 - Most of the images are not part of the drug labels, so it's Pillbox that's making the connection between image and product/data.  We have to be certain that the connection is correct.  Verifying these connections takes considerable time and resources.
2 - The data that the companies provide about their products sometimes changes between correct, incorrect, and ambiguous.  So we may be confident about the connection at one time, but that will change if the data provided by the companies changes.  Every time we update the data, it takes substantial time to solve these problems.
3 - Many medications are re-distributed.  One company manufacturers it and many may market/sell it.  All of them have to have a separate drug label, which means a separate record.  Their data frequently is not consistent.  It's becomes difficult to know who's information is correct and where to set the limits.
4 - Pillbox was built on parsing individual products about of the drug labels in an environment where the same product may be marketed by up to 40 other companies, meaning 40 other records.  Once you add the issues with inconsistent, ambiguous, and sometimes erroneous data, it becomes challenging.  We're planning to move to a system where we identify unique products and use that as the unique record.  We'll then point to labels from this records.  Because of #3 that will be become complex as well.

I think the best we could do now is release images with a date and a link to a single product, saying, "On this day, this image, was known to be connected to this product."  I think that has limited usefulness.  Then again developers are scraping the site for images.  The key goal for me is to be able to communicate clearly to developers the limitations of the data and images.  And that has to be more than docs on a wiki.

I'm interested in your thoughts on this.

**Comment by ghost** [comment]
Closing. Image library was made available for download 2014-02-24.

http://pillbox.nlm.nih.gov/developer.html#images
